### ISSUE TITLE
Help! Pack maker doesn't work!

### ISSUE THREAD

**Issue by xSekN** [RavinMaddHatter/Structura#145]
When I try to make an image this happens
![image](https://user-images.githubusercontent.com/85961799/202291086-a5a3a32f-eabd-4f57-b2a1-5602048a3bea.png)
in the command console it has an error message and it makes a new folder called what the pack name is and these are the files in it
![image](https://user-images.githubusercontent.com/85961799/202291416-e9e43393-ed25-4579-a39f-ca7339865925.png)
Anyone know anything about this? How to fix?

Using Version 1.5 Beta
Windows 10

**Comment by xSekN** [comment]
help

**Comment by Jimnav-png** [comment]
I had the same problem.

Are you saving the world in a OneDrive folder? That's what I was doing, and as it seems, there's a problem for windows when you export worlds, or in this case mcstructures into a OneDrive folder. It hadn't happen before, but I realized that the mcstructure and worlds I tried to export where 0kb. That means that the files are acutally empty, which of course causes Structura to don't work.

What I did is I exported the mcstructures into the downloads folder, so it's not on OneDrive, and only then it exported more than 0kB. 

I think the solution from Structure would be to have a pop up warning that could tell you that the file is empty, and maybe the cause is this one.

**Comment by Jimnav-png** [comment]
![202291416-e9e43393-ed25-4579-a39f-ca7339865925](https://user-images.githubusercontent.com/69730072/209481749-a8f71f83-db89-4c3b-8216-305288901243.png)

**Comment by corona6699** [comment]
I’m having the same issue with the file come back as 0kb and my exports are not going to one drive but a random folder and to desktop and nothing I can’t seem to fix it

**Comment by corona6699** [comment]
![Uploading 9B7456C5-868D-4845-B479-351D1E2D774E.jpeg…]()

**Comment by corona6699** [comment]
![BCAB3D2C-DDBB-4EA7-9133-E27C51F353E1](https://user-images.githubusercontent.com/121412468/209493397-b8bdb858-6922-47d5-9243-906e965f58bc.jpeg)

**Comment by Jimnav-png** [comment]
Desktop is on One Drive
That's why I chose Downloads

**Comment by Jimnav-png** [comment]
![Screenshot_20221226_075704_WhatsApp.jpg](https://user-images.githubusercontent.com/69730072/209514876-03d7e4ca-11dd-42b8-940c-12f031f06bad.jpg)

**Comment by corona6699** [comment]
> 

Okay I’m going to try that

**Comment by corona6699** [comment]
Thank you soooooo much
