### ISSUE TITLE
Error making pack

### ISSUE THREAD

**Issue by azimamdan** [RavinMaddHatter/Structura#25]
i suppose this is a bug.

I have the .exe file, the vanilla resource folder, and lookup folder in the same directory. But whenever i tried to make a pack after exporting the structure, it failed with error messages as below:

```
no rotation for chest found
no rotation for chest found
no rotation for chest found
no rotation for chest found
no rotation for barrel found
Exception in Tkinter callback
Traceback (most recent call last):
  File "structura.py", line 96, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 337, in block_name_to_uv
  File "armor_stand_class.py", line 312, in extend_uv_image
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 161, in runFromGui
  File "structura.py", line 99, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 337, in block_name_to_uv
  File "armor_stand_class.py", line 312, in extend_uv_image
IndexError: tuple index out of range
```

**Comment by RavinMaddHatter** [comment]
Can you post the structure file somewhere. i would like to see this one, this is an error i am not handling properly and i didnt put enough info in the log.

**Comment by azimamdan** [comment]
Here is the link for the structure file for your reference.

[https://we.tl/t-sLtkARd1p2](url)

![Screenshot (69)](https://user-images.githubusercontent.com/74825717/105639277-3d442d80-5eb2-11eb-9983-4140f3759a45.png)

**Comment by RavinMaddHatter** [comment]
Some things mojang does are weird. If you change to any shulker other than the "undyed" this would work.  if you want to "fix it" in your current download, open the shulker shulker_top_undyed.png change Image>mode> to RGB. Export as png. the drop down should be RGBA.

This breaks because my program expects RGBA files because they allow me to set transparency 

I will fix it in the next update...   you can download the file below and put it in Vanilla_Resource_Pack\textures\blocks replacing shulker_top_undyed.png on your local install.. that will fix it.
![shulker_top_undyed](https://user-images.githubusercontent.com/4407668/105643285-cbcd9600-5e43-11eb-9ecf-bfd729dee853.png)

**Comment by RavinMaddHatter** [comment]
Fixed in the next update
