### ISSUE TITLE
Some blocks prevent the app from generating the pack

### ISSUE THREAD

**Issue by Fluffy-Animal** [RavinMaddHatter/Structura#26]
if your exported structure contains one of the following blocks (there are many I will edit this as i find more) the pack won't generate:
-shulker box
-barrel
-grindstone
-extended piston

**Comment by RavinMaddHatter** [comment]
If you want a local work around. go into Vanilla_Resource_Pack\textures\blocks open the .tga files, export as png. 

If you know how to use git, branch and submit a PR and i will take it.

If anyone sees this bug before i get to it, i will take a pr on it gladly

**Comment by RavinMaddHatter** [comment]
Adding the fixed images here, getting ready for a patch of these, they are simple to fix

![grindstone_side](https://user-images.githubusercontent.com/4407668/105643378-6037f880-5e44-11eb-8903-101bed831a69.png)
![grindstone_pivot](https://user-images.githubusercontent.com/4407668/105643379-6037f880-5e44-11eb-9f7e-810e67686886.png)
![grindstone_round](https://user-images.githubusercontent.com/4407668/105643381-60d08f00-5e44-11eb-87ed-4e746fe95c76.png)
![shulker_top_undyed](https://user-images.githubusercontent.com/4407668/105643385-64641600-5e44-11eb-8f5a-5234cb7b5873.png)

Will be fixed in the next update

**Comment by ForestOfGold** [comment]
-grindstone_side
-stonecutter2_saw
-cactus_side
-seagrass_doubletall_top_a
-kelp_top
-reeds
-more to be added since I've encountered a different error

**Comment by RavinMaddHatter** [comment]
Fixed in 1.1.1
