### ISSUE TITLE
Texture bug type: Greyscale

### ISSUE THREAD

**Issue by ForestOfGold** [RavinMaddHatter/Structura#33]
Some textures, anywhere they're used, are in greyscale.
```
These are:
- water
- melon stem
- pumpkin stem
- vines
- grass
- sides and bottom of redstone dust
```
![image](https://user-images.githubusercontent.com/77603428/105684490-e175a680-5ea9-11eb-995c-3c0744baee79.png)

**Comment by voidredstone** [comment]
> If someone can edit the colors on this to make it look right, i will accept a PR or add it in and submit a PR on your behalf.
> 
> You can fix it in your local copy by modifying the texture files in Vanilla_Resource_Pack\textures\blocks\
> 
> If you cant figure out how to do a PR please attach the images to this bug and i will fix it and put it in the pack. They are rendered grey scale for the same reason redstone dust was in my very first version... the image is in grey scale.

![vines](https://user-images.githubusercontent.com/78044298/105890812-ba34eb80-6007-11eb-9adb-342154bb0ad8.png)
You can use the water_still.png instead of water_still_grey for a blue version.
![pumpkin_stem_connected](https://user-images.githubusercontent.com/78044298/105891738-e0a75680-6008-11eb-9f75-344f15068f62.png)
![melon_stem_disconnected](https://user-images.githubusercontent.com/78044298/105891741-e13fed00-6008-11eb-9ff7-fe352fe390c8.png)
![melon_stem_connected](https://user-images.githubusercontent.com/78044298/105891742-e1d88380-6008-11eb-9f3d-8dd386fee072.png)
![pumpkin_stem_disconnected](https://user-images.githubusercontent.com/78044298/105891743-e1d88380-6008-11eb-8f8a-63bd22bb16a3.png)
![grass_block_side](https://user-images.githubusercontent.com/78044298/105893687-4f85af00-600b-11eb-8f3f-d94c2ff1847a.png)
![redstone_wire](https://user-images.githubusercontent.com/78044298/105895120-06cef580-600d-11eb-8847-5417a6db1302.png)

I didn't consider the 16 dust states, so let me know if that needs doing.

**Comment by FondUnicycle** [comment]
Adding to Voidredstone comment, if the grass_carried.png is used, there's no need to erase the dirt part, it should work just fine as it is.

**Comment by RavinMaddHatter** [comment]
Merged
